# Generated by Django 5.0.6 on 2024-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panesbd',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Panes'),
        ),
    ]
